export const videoId='abcdefghijk',videoUrl=`https://www.youtube.com/watch?v=${videoId}`;
export const description='卵焼き（2人分）\n卵 2個\nA 砂糖 大さじ1/2\nA キッコーマンいつでも新鮮しぼりたて生しょうゆ 小さじ1';
export const videoRecipe={title:'卵焼き',category:'主菜',servings:2,minutes:null,ingredients:[{name:'卵',quantity:'2',unit:'個',group:'',quantitySource:'description'},{name:'砂糖',quantity:'1/2',unit:'大さじ',group:'A',quantitySource:'description'},{name:'キッコーマンいつでも新鮮しぼりたて生しょうゆ',quantity:'1',unit:'小さじ',group:'A',quantitySource:'caption'},{name:'油',quantity:'2',unit:'大さじ',group:'',quantitySource:'unknown'}],steps:['卵とAを混ぜる。','フライパンに油を熱して焼く。'],stepSources:[null,null],stepVideoSeconds:[12,65],memo:'',issues:[]};
export const playerHtml=(text=description,id=videoId,spec)=>`<script>var ytInitialPlayerResponse = ${JSON.stringify({videoDetails:{videoId:id,title:'卵焼きの作り方',shortDescription:text,lengthSeconds:'180'},...(spec?{storyboards:{playerStoryboardSpecRenderer:{spec}}}:{})})};</script>`;
export const geminiResponse=(recipe=videoRecipe)=>({candidates:[{finishReason:'STOP',content:{role:'model',parts:[{thought:true,text:'Hidden reasoning must not be parsed or displayed.'},{text:JSON.stringify({recipe:recipe?{...recipe,steps:recipe.steps.map((text,i)=>typeof text==='string'?{text,startSeconds:recipe.stepVideoSeconds?.[i]??null,photoSeconds:recipe.stepPhotoSeconds?.[i]??recipe.stepVideoSeconds?.[i]??null}:text)}:null,error:recipe?null:'読み取れませんでした'})}]}}]});
// Same shape as the watch page's yt-initial-data JSON script. The player may
// lack metadata even though the page contains a complete public description.
export const watchData=(text=description,id=videoId)=>({currentVideoEndpoint:{watchEndpoint:{videoId:id}},contents:{twoColumnWatchNextResults:{results:{results:{contents:[{videoPrimaryInfoRenderer:{title:{runs:[{text:'卵焼きの作り方'}]}}},{videoSecondaryInfoRenderer:{attributedDescription:{content:text}}}]}}}}});
export const watchHtml=(text=description,id=videoId,spec)=>`<script>var ytInitialPlayerResponse = {"playabilityStatus":{"status":"UNPLAYABLE"}};</script><script id="yt-initial-data" type="application/json">${JSON.stringify(watchData(text,id))}</script>`;

export const storyboardSpec=`https://i.ytimg.com/sb/${videoId}/storyboard3_L$L/$N.jpg?sqp=test|48#27#100#10#10#0#default#signature|320#180#36#3#3#5000#M$M#signature`;
