import {useEffect,useState,type ReactNode} from 'react';
export type User={id:string;email:string;name:string;avatarUrl?:string};
export type Session={user:User;local:boolean;logout:()=>Promise<void>};
export function Brand({small=false}:{small?:boolean}){return <div className={`uchino-brand${small?' small':''}`}><img src="/logo.svg" alt="うと鍋のアイコン"/><span>uchino</span></div>;}
function LoginBrand(){return <div className="login-brand"><img className="login-brand-icon" src="/logo.svg" alt=""/><span>uchino</span></div>;}
function GoogleMark(){return <svg width="20" height="20" viewBox="0 0 48 48" aria-hidden="true"><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5Z"/><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65Z"/><path fill="#FBBC05" d="M10.53 28.59A14.4 14.4 0 0 1 9.75 24c0-1.59.27-3.13.78-4.59l-7.98-6.19A23.8 23.8 0 0 0 0 24c0 3.87.93 7.53 2.56 10.78l7.97-6.19Z"/><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.91-5.8l-7.73-6c-2.15 1.45-4.92 2.3-8.18 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48Z"/></svg>;}
export function AuthGate({children}:{children:(session:Session)=>ReactNode}){
  const [user,setUser]=useState<User|null>(null),[local,setLocal]=useState(false),[loading,setLoading]=useState(true),[configured,setConfigured]=useState(false),[error,setError]=useState(''),[signingIn,setSigningIn]=useState(false);
  useEffect(()=>{const controller=new AbortController();
    void fetch('/api/auth/session',{cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(10000)])}).then(async response=>{if(!response.ok)throw new Error();const session=await response.json() as {configured:boolean;user:User|null};setConfigured(session.configured);setUser(session.user);if(session.user)localStorage.setItem('uchino-last-user',JSON.stringify(session.user));else setLocal(localStorage.getItem('uchino-device-mode')==='true');}).catch(()=>{if(controller.signal.aborted)return;try{const cached=localStorage.getItem('uchino-last-user');if(!navigator.onLine&&cached)setUser(JSON.parse(cached));else setLocal(localStorage.getItem('uchino-device-mode')==='true');}catch{}setError('通信を確認してください。端末に保存したレシピはオフラインでも使えます。');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    const reason=new URL(location.href).searchParams.get('auth_error');if(reason){setError(reason==='not_allowed'?'このアカウントには利用権限がありません。':'ログインできませんでした。もう一度お試しください。');history.replaceState(null,'','/');}
    return()=>controller.abort();
  },[]);
  // A request came back 401: ask the server once more and, only if the session
  // is really gone, fall back to the sign-in screen. Local edits stay pending.
  useEffect(()=>{if(!user)return;let checking=false;const recheck=()=>{if(checking||!navigator.onLine)return;checking=true;void fetch('/api/auth/session',{cache:'no-store',signal:AbortSignal.timeout(10000)}).then(async response=>{if(!response.ok)return;const session=await response.json() as {user:User|null};if(!session.user){localStorage.removeItem('uchino-last-user');setUser(null);}}).catch(()=>{}).finally(()=>{checking=false;});};window.addEventListener('uchino:session-expired',recheck);return()=>window.removeEventListener('uchino:session-expired',recheck);},[user]);
  async function logout(){if(user){const response=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error('ログアウトできませんでした。');}localStorage.removeItem('uchino-last-user');localStorage.removeItem('uchino-device-mode');setUser(null);setLocal(false);}
  if(loading)return <main className="login"><p className="login-status" role="status">ログイン状態を確認しています…</p></main>;
  if(user||local)return <>{children({user:user??{id:'guest',email:'',name:'この端末'},local:!user,logout})}</>;
  // Same layout as uchiwake's sign-in, with the concept line in Soft Orbit colors.
  return <main className="login"><div className="login-panel"><LoginBrand/><h1><span className="login-rainbow">AIで整理。</span><br/>うちのレシピ。</h1><div className="login-actions"><button className="google-sign-in" disabled={!configured||signingIn} aria-busy={signingIn} onClick={()=>{setSigningIn(true);location.assign('/api/auth/google');}}><GoogleMark/><span>{signingIn?'Googleに移動しています…':'Googleでログイン'}</span></button>{error&&<p className="login-error" role="alert">{error}</p>}{!configured&&<p className="login-status">Googleログインは現在準備中です。</p>}</div></div></main>;
}
