import {createRoot} from 'react-dom/client';
import {AuthGate} from './auth';
import {App} from './app';
import {registerPWA} from './pwa';
import './styles.css';
import './kondo-style.css';
import './theme.css';
import './login.css';
import './uchino.css';
import './settings.css';
import './studio-action.css';
import './import-effects.css';
import './recipe-import.css';
import './shopping.css';
createRoot(document.getElementById('root')!).render(<AuthGate>{session=><App key={session.user.id} session={session}/>}</AuthGate>);
void registerPWA().catch(()=>{});
