import {Plus,Trash2} from 'lucide-react';
import {categories,recipePhoto,type Recipe} from './domain';
import {RecipePhotoPicker} from './recipe-photo-picker';
export function RecipeEditor({value,onChange,onSubmit,error,onRemoveItem,onPhotoBusyChange}:{value:Recipe;onChange:(recipe:Recipe)=>void;onSubmit:()=>void;error:string;onPhotoBusyChange?:(busy:boolean)=>void;onRemoveItem?:(kind:'ingredients'|'steps',index:number)=>void}){
  const update=(change:Partial<Recipe>)=>onChange({...value,...change});
  return <form id="recipe-form" className="form recipe-form" onSubmit={e=>{e.preventDefault();onSubmit();}}>
    {error&&<p role="alert" className="form-error">{error}</p>}
    <RecipePhotoPicker photo={recipePhoto(value)} onChange={photo=>update({photo})} onBusyChange={onPhotoBusyChange}/>
    <label className="field">レシピ名<input data-import-field="title" required maxLength={200} value={value.title} placeholder="レシピ名を入力" onChange={e=>update({title:e.target.value})}/></label>
    <div className="field-pair"><label className="field">カテゴリ<select data-import-field="category" value={value.category} onChange={e=>update({category:e.target.value as Recipe['category']})}>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label className="field">人数<input data-import-field="servings" type="number" min={1} max={100} required inputMode="numeric" value={value.servings} onChange={e=>update({servings:Number(e.target.value)})}/></label></div>
    <label className="field">調理時間（分）<input data-import-field="minutes" type="number" min={1} max={10080} inputMode="numeric" value={value.minutes??''} placeholder="未設定" onChange={e=>update({minutes:e.target.value?Number(e.target.value):null})}/></label>
    <section className="editor-section"><div className="section-head"><h3>材料</h3><button className="text-action" type="button" disabled={value.ingredients.length>=100} onClick={()=>update({ingredients:[...value.ingredients,{name:'',quantity:'',unit:''}]})}><Plus size={16}/>追加</button></div><div className="ingredient-column-labels"><span>材料名</span><span>分量</span><span>単位</span></div>{value.ingredients.map((i,index)=><div className="ingredient-edit" key={index}><input data-import-field={`ingredients.${index}.name`} aria-label={`材料${index+1}`} required maxLength={200} value={i.name} placeholder="玉ねぎ" onChange={e=>update({ingredients:value.ingredients.map((v,n)=>n===index?{...v,name:e.target.value}:v)})}/><input data-import-field={`ingredients.${index}.quantity`} aria-label={`分量${index+1}`} maxLength={100} value={i.quantity} placeholder="1/2" onChange={e=>update({ingredients:value.ingredients.map((v,n)=>n===index?{...v,quantity:e.target.value}:v)})}/><input data-import-field={`ingredients.${index}.unit`} aria-label={`単位${index+1}`} maxLength={50} value={i.unit} placeholder="個" onChange={e=>update({ingredients:value.ingredients.map((v,n)=>n===index?{...v,unit:e.target.value}:v)})}/><button type="button" className="row-icon" disabled={value.ingredients.length<=1} aria-label={`材料${index+1}を削除`} onClick={()=>onRemoveItem?onRemoveItem('ingredients',index):update({ingredients:value.ingredients.filter((_,n)=>n!==index)})}><Trash2 size={17}/></button></div>)}</section>
    <section className="editor-section"><div className="section-head"><h3>作り方</h3><button className="text-action" type="button" disabled={value.steps.length>=100} onClick={()=>update({steps:[...value.steps,'']})}><Plus size={16}/>追加</button></div>{value.steps.map((step,index)=><div className="step-edit" key={index}><span>{index+1}</span><textarea data-import-field={`steps.${index}`} aria-label={`手順${index+1}`} required maxLength={5000} value={step} rows={3} placeholder="作り方を入力" onChange={e=>update({steps:value.steps.map((v,n)=>n===index?e.target.value:v)})}/><button type="button" className="row-icon" disabled={value.steps.length<=1} aria-label={`手順${index+1}を削除`} onClick={()=>onRemoveItem?onRemoveItem('steps',index):update({steps:value.steps.filter((_,n)=>n!==index)})}><Trash2 size={17}/></button></div>)}</section>
    <label className="field">参照URL<input type="url" maxLength={2048} value={value.sourceUrl} placeholder="https://" onChange={e=>update({sourceUrl:e.target.value})}/></label>
    <label className="field">メモ<textarea data-import-field="memo" maxLength={10000} value={value.memo} rows={3} placeholder="メモを入力..." onChange={e=>update({memo:e.target.value})}/></label>
    <button className="visually-hidden" type="submit" tabIndex={-1}>保存</button>
  </form>;
}
